### ISSUE TITLE
Move msg and srv to appropriated packages

### ISSUE THREAD

**Issue by 0x72D0** [sonia-auv/sonia_msgs#2]
## Expected Enhancement
We put all the msg and srv in each package or having a package that contains all msg and srv, but not both.

## Current Behavior
Some package like proc_image_processing use sonia_msgs and other use local msg and srv.

## Possible Solution
Move all msg and srv in the appropriate package or all package use a common msg and srv.

## Comments
This is a remake of the issue #1 to avoid spamming old members

**Comment by gauthiermartin** [comment]
This solution will not be viable anymore .... we will need to extract msg from packages to have them in the same repository so it will be easily available through all packages for CI/CD and Containerizing purposes
