### ISSUE TITLE
Extract custom ROS messages from node into sonia_msgs module

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/sonia_msgs#3]
Since we are packaging our module into single docker containers we will need to extract custom message into another node to ease up unit and integration testing effort

**Comment by coumarc9** [comment]
The following repositories will be analyzed:

- [ ] controller_mission
- [ ] deep_detector
- [ ] proc_actuators
- [ ] proc_control
- [ ] proc_hydrophone
- [ ] proc_image_processing
- [ ] proc_mapping
- [ ] proc_navigation
- [ ] proc_sonar
- [ ] proc_ura
- [ ] provider_actuators
- [ ] provider_dvl
- [ ] provider_hydrophone
- [ ] provider_imu
- [ ] provider_kill_mission
- [ ] provider_power
- [ ] provider_sonar
- [ ] provider_system
- [ ] provider_thruster
- [ ] provider_vision

**Comment by coumarc9** [comment]
All verification done. Action required in repos (issues opened for each and attached to project)

**Comment by coumarc9** [comment]
Progression:
- [ ] deep_detector
- [ ] proc_actuators
- [ ] proc_control
- [ ] proc_hydrophone
- [ ] proc_image_processing
- [ ] proc_mapping
- [ ] proc_navigation
- [ ] proc_sonar
- [ ] proc_ura
- [ ] provider_actuators
- [ ] provider_dvl
- [ ] provider_hydrophone
- [ ] provider_imu
- [ ] provider_kill_mission
- [ ] provider_power
- [ ] provider_sonar
- [ ] provider_system
- [ ] provider_thruster
- [ ] provider_vision
- [ ] interface_RS485

**Comment by coumarc9** [comment]
All done!
